name: Build and Push to ECR

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    

    - name: Build Docker image
      run: |
        docker build -t simple-web .

    # - name: Tag Docker image
    #   run: |
    #     IMAGE_URI=${{ secrets.ECR_REPOSITORY }}:latest
    #     docker tag simple-web $IMAGE_URI
    #     echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    # - name: Push Docker image to ECR
    #   run: |
    #     docker push $IMAGE_URI
